### ISSUE TITLE
lot's of /dev/null permission denied

### ISSUE THREAD

**Issue by stutiredboy** [simonvanderveldt/lxc-debian-wheezy-template#3]
after 
# lxc-create -n testing -t debian-wheezy

i run lxc-start, but got lot's of /dev/null: Permission denied.
# lxc-start -n testing

INIT: version 2.88 booting
/etc/init.d/rc: 424: /lib/lsb/init-functions: cannot create /dev/null: Permission denied
/etc/init.d/rc: 85: /etc/init.d/rc: cannot create /dev/null: Permission denied
/etc/rcS.d/S01hostname.sh: 424: /lib/lsb/init-functions: cannot create /dev/null: Permission denied
/etc/rcS.d/S01mountkernfs.sh: 424: /lib/lsb/init-functions: cannot create /dev/null: Permission denied
/etc/rcS.d/S02mountdevsubfs.sh: 424: /lib/lsb/init-functions: cannot create /dev/null: Permission denied
/etc/rcS.d/S02mountdevsubfs.sh: 378: /etc/rcS.d/S02mountdevsubfs.sh: cannot create /dev/null: Permission denied
/etc/rcS.d/S02mountdevsubfs.sh: 379: /etc/rcS.d/S02mountdevsubfs.sh: cannot create /dev/null: Permission denied
/etc/rcS.d/S04checkroot.sh: 424: /lib/lsb/init-functions: cannot create /dev/null: Permission denied
Activating swap.../etc/rcS.d/S04checkroot.sh: 73: /etc/rcS.d/S04checkroot.sh: cannot create /dev/null: Permission denied
/etc/rcS.d/S04checkroot.sh: 215: /etc/rcS.d/S04checkroot.sh: cannot create /dev/null: Permission denied
failed.
/etc/rcS.d/S04checkroot.sh: 279: /etc/rcS.d/S04checkroot.sh: cannot create /dev/null: Permission denied
mount: can't find / in /etc/fstab or /etc/mtab
Creating compatibility symlink from /etc/mtab to /proc/mounts. .../etc/rcS.d/S04checkroot.sh: 215: /etc/rcS.d/S04checkroot.sh: cannot create /dev/null: Permission denied
 (warning).
/etc/rcS.d/S04checkroot.sh: 31: /etc/rcS.d/S04checkroot.sh: cannot create /dev/null: Permission denied
/etc/rcS.d/S05checkroot-bootclean.sh: 424: /lib/lsb/init-functions: cannot create /dev/null: Permission denied
/etc/rcS.d/S05checkroot-bootclean.sh: 171: /etc/rcS.d/S05checkroot-bootclean.sh: cannot create /dev/null: Permission denied
/etc/rcS.d/S05mtab.sh: 424: /lib/lsb/init-functions: cannot create /dev/null: Permission denied
/etc/init.d/mountkernfs.sh: 424: /lib/lsb/init-functions: cannot create /dev/null: Permission denied
/etc/init.d/mountkernfs.sh: 275: /etc/init.d/mountkernfs.sh: cannot open /dev/null: Permission denied
/etc/init.d/mountkernfs.sh: 277: /etc/init.d/mountkernfs.sh: cannot open /dev/null: Permission denied
/etc/init.d/mountkernfs.sh: 275: /etc/init.d/mountkernfs.sh: cannot open /dev/null: Permission denied
/etc/init.d/mountkernfs.sh: 277: /etc/init.d/mountkernfs.sh: cannot open /dev/null: Permission denied
/etc/init.d/mountkernfs.sh: 275: /etc/init.d/mountkernfs.sh: cannot open /dev/null: Permission denied
/etc/init.d/mountkernfs.sh: 277: /etc/init.d/mountkernfs.sh: cannot open /dev/null: Permission denied
/etc/init.d/mountkernfs.sh: 275: /etc/init.d/mountkernfs.sh: cannot open /dev/null: Permission denied
/etc/init.d/mountkernfs.sh: 277: /etc/init.d/mountkernfs.sh: cannot open /dev/null: Permission denied
/etc/init.d/mountkernfs.sh: 424: /lib/lsb/init-functions: cannot create /dev/null: Permission denied
/etc/init.d/mountdevsubfs.sh: 424: /lib/lsb/init-functions: cannot create /dev/null: Permission denied
/etc/init.d/mountdevsubfs.sh: 275: /etc/init.d/mountdevsubfs.sh: cannot open /dev/null: Permission denied
/etc/init.d/mountdevsubfs.sh: 277: /etc/init.d/mountdevsubfs.sh: cannot open /dev/null: Permission denied
/etc/init.d/mountdevsubfs.sh: 275: /etc/init.d/mountdevsubfs.sh: cannot open /dev/null: Permission denied
/etc/init.d/mountdevsubfs.sh: 277: /etc/init.d/mountdevsubfs.sh: cannot open /dev/null: Permission denied
/etc/init.d/mountdevsubfs.sh: 424: /lib/lsb/init-functions: cannot create /dev/null: Permission denied
/etc/rcS.d/S05mtab.sh: 275: /etc/rcS.d/S05mtab.sh: cannot open /dev/null: Permission denied
/etc/rcS.d/S05mtab.sh: 277: /etc/rcS.d/S05mtab.sh: cannot open /dev/null: Permission denied
/etc/rcS.d/S05mtab.sh: 275: /etc/rcS.d/S05mtab.sh: cannot open /dev/null: Permission denied
/etc/rcS.d/S05mtab.sh: 277: /etc/rcS.d/S05mtab.sh: cannot open /dev/null: Permission denied
/etc/rcS.d/S05mtab.sh: 275: /etc/rcS.d/S05mtab.sh: cannot open /dev/null: Permission denied
/etc/rcS.d/S05mtab.sh: 277: /etc/rcS.d/S05mtab.sh: cannot open /dev/null: Permission denied
/etc/rcS.d/S05mtab.sh: 275: /etc/rcS.d/S05mtab.sh: cannot open /dev/null: Permission denied
/etc/rcS.d/S05mtab.sh: 277: /etc/rcS.d/S05mtab.sh: cannot open /dev/null: Permission denied
Mount point '/dev/console' does not exist. Skipping mount. .../etc/rcS.d/S05mtab.sh: 215: /etc/rcS.d/S05mtab.sh: cannot create /dev/null: Permission denied
 (warning).
Mount point '/dev/tty1' does not exist. Skipping mount. .../etc/rcS.d/S05mtab.sh: 215: /etc/rcS.d/S05mtab.sh: cannot create /dev/null: Permission denied
 (warning).
Mount point '/dev/tty2' does not exist. Skipping mount. .../etc/rcS.d/S05mtab.sh: 215: /etc/rcS.d/S05mtab.sh: cannot create /dev/null: Permission denied
 (warning).
Mount point '/dev/tty3' does not exist. Skipping mount. .../etc/rcS.d/S05mtab.sh: 215: /etc/rcS.d/S05mtab.sh: cannot create /dev/null: Permission denied
 (warning).
Mount point '/dev/tty4' does not exist. Skipping mount. .../etc/rcS.d/S05mtab.sh: 215: /etc/rcS.d/S05mtab.sh: cannot create /dev/null: Permission denied
 (warning).
Mount point '/dev/tty5' does not exist. Skipping mount. .../etc/rcS.d/S05mtab.sh: 215: /etc/rcS.d/S05mtab.sh: cannot create /dev/null: Permission denied
 (warning).
Mount point '/dev/tty6' does not exist. Skipping mount. .../etc/rcS.d/S05mtab.sh: 215: /etc/rcS.d/S05mtab.sh: cannot create /dev/null: Permission denied
 (warning).
/etc/rcS.d/S05mtab.sh: 275: /etc/rcS.d/S05mtab.sh: cannot open /dev/null: Permission denied
/etc/rcS.d/S05mtab.sh: 277: /etc/rcS.d/S05mtab.sh: cannot open /dev/null: Permission denied
Mount point '/dev/ptmx' does not exist. Skipping mount. .../etc/rcS.d/S05mtab.sh: 215: /etc/rcS.d/S05mtab.sh: cannot create /dev/null: Permission denied
 (warning).
/etc/rcS.d/S05mtab.sh: 275: /etc/rcS.d/S05mtab.sh: cannot open /dev/null: Permission denied
/etc/rcS.d/S05mtab.sh: 277: /etc/rcS.d/S05mtab.sh: cannot open /dev/null: Permission denied

login to the container with root

root@testing:~# ls -alh /dev/null
crw-rw-rw- 1 root root 1, 3 Jun  3 14:59 /dev/null
root@testing:~# /etc/init.d/ssh start
/etc/init.d/ssh: 17: /etc/init.d/ssh: cannot create /dev/null: Permission denied
root@testing:~#

need your help. thanks.

**Comment by simonvanderveldt** [comment]
Hmm, I've never had this before. Can you do a cat /dev/null (after you get these issues) and check if it's still empty/null?
Could be it's actually not empty/null anymore...

Noticed you posted to lxc-users as well (http://sourceforge.net/mailarchive/message.php?msg_id=31117879), did the answer there get you anywhere?

**Comment by stutiredboy** [comment]
I think i have got the point. I mount the partition with nodev option. thanks.

**Comment by simonvanderveldt** [comment]
Ah, that explains it :)
I'll close the issue.
