### ISSUE TITLE
Alloow $arch to be set

### ISSUE THREAD

**Issue by nikmartin** [simonvanderveldt/lxc-debian-wheezy-template#4]
The code:

```
    arch=$(arch)
    if [ "$arch" == "x86_64" ]; then
        arch=amd64
    fi

    if [ "$arch" == "i686" ]; then
        arch=i386
    fi

    if [ "$arch" == "armv5tel" ]; then
        arch=armel
    fi
```

Does not allow $arch to be set  via an environment. commenting out `arch=$(arch)` allows you to set the arhcitecture.  The script should check if $arch is set first, to allow other architectures to be used for containers

**Comment by simonvanderveldt** [comment]
First of all, sorry for my very slow response. Reall life has been busy ;)

Anyway, good catch! I'm labelling this as enhancement.

I do wonder though, shouldn't we use lxc.conf for things like this?
See the [lxc.conf manpage](http://manpages.ubuntu.com/manpages/karmic/man5/lxc.conf.5.html) (debian's manpages site is down, so linking to Ubuntu)
