### ISSUE TITLE
Problem when using your template

### ISSUE THREAD

**Issue by chrisduong** [simonvanderveldt/lxc-debian-wheezy-template#9]
Hi,

It would be great if you could help me.
I got this message when using your new template.

Note: Usually the template option is called with a configuration
file option too, mostly to configure the network.
For more information look at lxc.conf (5)

/usr/bin/lxc-create: 276: /usr/bin/lxc-create: /usr/share/lxc/templates/lxc-debian-new: not found
failed to execute template 'debian-new'
aborted

I'm using Debian Wheezy amd64.  /usr/share/lxc/templates/lxc-debian-new is your new template and it exists
Thanks

**Comment by simonvanderveldt** [comment]
Hi Chris,

What was the exact command you entered?
And can you post the result of `ls -l /usr/share/lxc/templates/`?

Final question ;)
Which file did you copy there/rename to lxc-debian-new?

Best regards,
Simon

**Comment by chrisduong** [comment]
Hi,

# ls -l /usr/share/lxc/templates/

-rwxr-xr-x 1 root root     12022 Aug 23  2012 lxc-altlinux
-rwxr-xr-x 1 root root     13467 Aug 23  2012 lxc-archlinux
-rwxr-xr-x 1 root root     23563 Aug 23  2012 lxc-debconf
drwxr-xr-x 2 root root      4096 Dec  2 15:11 lxc-debconf.d
lrwxrwxrwx 1 root root        11 Aug 23  2012 lxc-debian -> lxc-debconf
lrwxrwxrwx 1 root root        13 Aug 23  2012 lxc-debian.d -> lxc-debconf.d
-rwxr-xr-x 1 root root     11117 Dec  2 15:58 lxc-debian-new
-rwxr-xr-x 1 root root      7149 Dec  2 16:42 lxc-debian-orig
-rwxr-xr-x 1 root root      7896 Dec  2 15:30 lxc-debian-wheezy
-rwxr-xr-x 1 root root      9983 Aug 23  2012 lxc-fedora
-rwxr-xr-x 1 root root     10135 Aug 23  2012 lxc-opensuse
lrwxrwxrwx 1 root root        11 Aug 23  2012 lxc-progress -> lxc-debconf
lrwxrwxrwx 1 root root        13 Aug 23  2012 lxc-progress.d -> lxc-debconf.d
-rwxr-xr-x 1 root root      4092 Aug 23  2012 lxc-sshd
-rwxr-xr-x 1 root root      7725 Aug 23  2012 lxc-ubuntu-cloud
- I used lxc-debian-0.7.5-5-debian template for my lxc version 0.8.0 rc5

**Comment by simonvanderveldt** [comment]
Hi Chris,

Can you try it again with the `lxc-debian-wheezy-robvdhoeven` template? That's the template that works at the moment.

**Comment by chrisduong** [comment]
It worked. Thnx. :)

**Comment by simonvanderveldt** [comment]
Perfect! :)
FYI, there are now some basic getting started/how to use instructions in the readme.
